apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweetqueuebinding
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "sidoosxpdemo"
  - name: storageAccessKey
    secretKeyRef:
      name: STORAGEACCESSKEY
      key: STORAGEACCESSKEY
  - name: queue
    value: "tweets-queue"
auth:
  secretStore: envvar-secret-store