apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tweetsBinding
spec:
  type: bindings.twitter
  version: v1
  metadata:
  - name: consumerKey
    secretKeyRef:
      name: consumerKey
      key: consumerKey # twitter api consumer key, required
  - name: consumerSecret
    secretKeyRef:
      name: consumerSecret
      key: consumerSecret # twitter api consumer secret, required
  - name: accessToken
    secretKeyRef:
      name: accessToken
      key: accessToken # twitter api access token, required
  - name: accessSecret
    secretKeyRef:
      name: accessSecret
      key: accessSecret # twitter api access secret, required
  - name: query
    value: "#cop26" # your search query, required
auth:
  secretStore: my-secrets-store